// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'pref-app-theme'
  | 'pref-description'
  | 'pref-enable'
  | 'pref-help'
  | 'pref-reader-apply-dark'
  | 'pref-reader-apply-follow'
  | 'pref-reader-apply-light'
  | 'pref-reader-background-theme'
  | 'pref-reader-content-theme'
  | 'pref-reader-left-sidebar-theme'
  | 'pref-reader-sidebar-theme'
  | 'pref-reader-toolbar-theme'
  | 'pref-section-app'
  | 'pref-section-reader'
  | 'pref-theme-dark'
  | 'pref-theme-follow'
  | 'pref-theme-light'
  | 'pref-title'
  | 'prefs-title'
  | 'startup-begin'
  | 'startup-finish';
